# Generated by Django 2.0.6 on 2018-06-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('Game_No', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Abhinav', models.IntegerField()),
                ('Harshith', models.IntegerField()),
                ('Rajath', models.IntegerField()),
                ('Winner', models.CharField(max_length=50)),
                ('deal', models.CharField(default='N', max_length=1)),
            ],
        ),
    ]
