# Generated by Django 2.0.6 on 2018-06-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scores',
            options={'verbose_name_plural': 'Scores'},
        ),
    ]
