# Generated by Django 2.0.6 on 2018-06-02 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20180602_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
