# Generated by Django 2.0.5 on 2018-06-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_auto_20180602_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='Session',
            field=models.IntegerField(default=0),
        ),
    ]
